hw2: main.o BinaryNode.o BinarySearchTree.o
	g++ -std=c++11 main.o BinaryNode.o BinarySearchTree.o -o hw2

main.o: main.cpp
	g++ -c main.cpp

BinaryNode.o: BinaryNode.cpp BinaryNode.h
	g++ -c BinaryNode.cpp BinaryNode.h

BinarySearchTree.o: BinarySearchTree.cpp BinarySearchTree.h
	g++ -c BinarySearchTree.cpp BinarySearchTree.h